# typed: true
# frozen_string_literal: true

# This file was generated by Brewtap. DO NOT EDIT.
class Jjava < Formula
  desc "Jupyter kernel for java notebooks"
  homepage "https://github.com/dflib/jjava"
  url "https://github.com/dflib/jjava/releases/download/1.0-a4/jjava-1.0-a4-kernelspec.zip"
  version "1.0-a4"
  sha256 "097f9a3db2ae77d22971bf7d041850c216f8b2a4da9cffda65a9334a6077bc12"
  license "MIT"

  depends_on "expect" => :test
  depends_on "jupyterlab"

  def install
    libexec.install Dir["*.jar"]
    config = buildpath/"kernel.json"
    inreplace config, "{resource_dir}", libexec
    system "jupyter kernelspec install #{buildpath} --config=#{config} --sys-prefix --name=java"
  end

  test do
    jupyter = Formula["jupyterlab"].opt_bin/"jupyter"
    assert_match " java ", shell_output("#{jupyter} kernelspec list")

    (testpath/"console.exp").write <<~EOS
      spawn #{jupyter} console --kernel=java
      expect -timeout 30 "In "
      send "System.out.println(\\\"Hello world!\\\");\r"
      expect -timeout 10 "In "
      send "\u0004"
      expect -timeout 10 "exit"
      send "y\r"
      EOS
    output = shell_output("expect -f console.exp")
    assert_match "JJava kernel #{version}", output
    assert_match "Hello world!", output
  end

  def caveats
    <<~EOS
      Although JJava doesn't depend on java, it requires jre>=11 to run.
      Make sure you have one in your PATH.
    EOS
  end
end
